### ISSUE TITLE
Problem integrating gridlayer.googlemutant to leaflet map

### ISSUE THREAD

**Issue by srunnithan** [jieter/leaflet.layerscontrol-minimap#13] opened 2019-03-11 14:18 UTC
Hi,

I have a leaflet map container on to which I am loading gridlayer.googlemutant as background layer.
Map is loading but some tile is missing on the left hand side(near to the google icon).

  gMiniMap = L.map(sMiniMapID, { dragging: false, zoomControl: false }).fitWorld();
        gMiniMap.on({
            zoomend: function () {
            }
        }); 

  oMiniBackgroundLayer = L.gridLayer.googleMutant({
            type: 'roadmap'	// valid values are 'roadmap', 'satellite', 'terrain' and 'hybrid'
        });
 gMiniMap.addLayer(oMiniBackgroundLayer);

![Googlemapbackgroundlayer-issue](https://user-images.githubusercontent.com/48443928/54130363-27393b00-4408-11e9-9a5e-f73c4f7edc4c.PNG)

**Comment by jieter** [comment] 2019-08-21 10:56
seems to be a duplicate of #7.

**Closed by jieter** 2019-08-21 10:56 UTC
